import React, { useState, useEffect } from 'react';
import { Platform, TrendReport, Language } from '../types';
import { Icons } from './Icon';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  report: TrendReport | null;
  platform: Platform;
  language: Language;
}

const ExportModal: React.FC<ExportModalProps> = ({ isOpen, onClose, report, platform, language }) => {
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    setCopied(false);
  }, [isOpen, platform]);

  if (!isOpen || !report) return null;

  const labels = {
    title: language === 'zh' ? '导出预览' : 'Export Preview',
    close: language === 'zh' ? '关闭' : 'Close',
    copy: language === 'zh' ? '复制内容' : 'Copy to Clipboard',
    copied: language === 'zh' ? '已复制!' : 'Copied!',
    cancel: language === 'zh' ? '取消' : 'Cancel'
  };

  const generateContent = () => {
    const header = `${report.topic} Weekly Digest - ${report.date}`;
    
    if (platform === 'dingtalk') {
      // DingTalk Markdown Format
      let md = `# ${header}\n\n`;
      report.items.forEach((item, index) => {
        md += `### ${index + 1}. ${item.title}\n`;
        md += `> **Summary**: ${item.summary}\n\n`;
        md += `**Impact**: ${item.impact}\n\n`;
        md += `**Takeaway**: ${item.takeaway}\n\n`;
        if (item.sources.length > 0) {
            md += `**Sources**: `;
            md += item.sources.map(s => `[${s.title}](${s.uri})`).join(' | ');
            md += `\n\n`;
        }
        md += `---\n\n`;
      });
      md += `*Generated by TrendRadar AI*`;
      return md;
    } else {
      // WeChat Text Format (Clean Text with spacing)
      let text = `【${header}】\n\n`;
      report.items.forEach((item, index) => {
        text += `📌 ${index + 1}. ${item.title}\n`;
        text += `📝 ${item.summary}\n`;
        text += `💡 Impact: ${item.impact}\n`;
        text += `🚀 Takeaway: ${item.takeaway}\n`;
        if (item.sources.length > 0) {
           text += `🔗 Sources: ${item.sources.map(s => s.title).join(', ')}\n`;
        }
        text += `\n`;
      });
      text += `--- TrendRadar AI ---`;
      return text;
    }
  };

  const content = generateContent();

  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
      <div className="bg-white rounded-2xl w-full max-w-2xl shadow-2xl flex flex-col max-h-[90vh]">
        <div className="p-6 border-b border-slate-100 flex justify-between items-center">
          <h2 className="text-xl font-bold text-slate-800 flex items-center gap-2">
            {platform === 'dingtalk' ? 'DingTalk Markdown' : 'WeChat Text'} {labels.title}
          </h2>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-600 transition-colors">
            {labels.close}
          </button>
        </div>
        
        <div className="p-6 overflow-y-auto bg-slate-50 font-mono text-sm text-slate-600 whitespace-pre-wrap">
          {content}
        </div>

        <div className="p-6 border-t border-slate-100 flex justify-end gap-3">
          <button 
            onClick={onClose}
            className="px-4 py-2 rounded-lg text-slate-600 hover:bg-slate-100 font-medium transition-colors"
          >
            {labels.cancel}
          </button>
          <button 
            onClick={handleCopy}
            className={`flex items-center gap-2 px-6 py-2 rounded-lg font-bold text-white transition-all transform active:scale-95 ${
              copied ? 'bg-green-600' : platform === 'dingtalk' ? 'bg-blue-600 hover:bg-blue-700' : 'bg-emerald-600 hover:bg-emerald-700'
            }`}
          >
            {copied ? <Icons.Check className="w-4 h-4" /> : <Icons.Copy className="w-4 h-4" />}
            {copied ? labels.copied : labels.copy}
          </button>
        </div>
      </div>
    </div>
  );
};

export default ExportModal;
